const INITIAL_BALANCE = 500;
const DIFFICULTY = 3;
const MINE_RATE = 3000;
const MINING_REWARD = 50;
const TRANSACTION_FEE = 1;

module.exports = { INITIAL_BALANCE, DIFFICULTY, MINE_RATE, MINING_REWARD, TRANSACTION_FEE };